CREATE TABLE users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  profile_image VARCHAR(255),
  password VARCHAR(255) NOT NULL
);